name: Node CI

on:
  push:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Node.js version
        id: node-version
        run: echo "::set-output name=version::$(cat .node-version)"
      - name: Setup Node.js ${{ steps.node-version.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version.version }}
      - name: Get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Generate
        run: yarn generate
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LAST_FM_USER: ${{ secrets.LAST_FM_USER }}
          LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
